// content/names.js
// Hardcoded fallback list generated from Wikipedia.
// The background service worker refreshes this daily via chrome.storage.local.
// Sorted longest-first so the regex engine tries longer names before shorter ones.
// Run scripts/update.py to refresh this file.

const HARDCODED_NAMES = [
  { name: "Mette-Marit, Crown Princess of Norway", anchor: "Mette-Marit,_Crown_Princess_of_Norway" },
  { name: "Princess Sofia, Duchess of Värmland", anchor: "Princess_Sofia,_Duchess_of_Värmland" },
  { name: "Lynn Forester de Rothschild", anchor: "Lynn_Forester_de_Rothschild" },
  { name: "Andrew Mountbatten-Windsor", anchor: "Andrew_Mountbatten-Windsor" },
  { name: "Sultan Ahmed bin Sulayem", anchor: "Sultan_Ahmed_bin_Sulayem" },
  { name: "Andrés Pastrana Arango", anchor: "Andrés_Pastrana_Arango" },
  { name: "Anastasiya Siroochenko", anchor: "Anastasiya_Siroochenko" },
  { name: "Tsakhiagiin Elbegdorj", anchor: "Tsakhiagiin_Elbegdorj" },
  { name: "Robert F. Kennedy Jr.", anchor: "Robert_F._Kennedy_Jr." },
  { name: "Francisco D'Agostino", anchor: "Francisco_D'Agostino" },
  { name: "Robert Lawrence Kuhn", anchor: "Robert_Lawrence_Kuhn" },
  { name: "Ariane de Rothschild", anchor: "Ariane_de_Rothschild" },
  { name: "Eva Andersson-Dubin", anchor: "Eva_Andersson-Dubin" },
  { name: "Mohammed bin Salman", anchor: "Mohammed_bin_Salman" },
  { name: "Edward Jay Epstein", anchor: "Edward_Jay_Epstein" },
  { name: "Shelley Anne Lewis", anchor: "Shelley_Anne_Lewis" },
  { name: "George J. Mitchell", anchor: "George_J._Mitchell" },
  { name: "Hardeep Singh Puri", anchor: "Hardeep_Singh_Puri" },
  { name: "Joshua Cooper Ramo", anchor: "Joshua_Cooper_Ramo" },
  { name: "David Copperfield", anchor: "David_Copperfield" },
  { name: "Steven Hoffenberg", anchor: "Steven_Hoffenberg" },
  { name: "Thorbjørn Jagland", anchor: "Thorbjørn_Jagland" },
  { name: "John de Jongh Jr.", anchor: "John_de_Jongh_Jr." },
  { name: "Nicole Junkermann", anchor: "Nicole_Junkermann" },
  { name: "Ghislaine Maxwell", anchor: "Ghislaine_Maxwell" },
  { name: "Annabelle Neilson", anchor: "Annabelle_Neilson" },
  { name: "Christopher Poole", anchor: "Christopher_Poole" },
  { name: "V.S. Ramachandran", anchor: "V.S._Ramachandran" },
  { name: "Virginia Giuffre", anchor: "Virginia_Giuffre" },
  { name: "Terje Rød-Larsen", anchor: "Terje_Rød-Larsen" },
  { name: "Kathryn Ruemmler", anchor: "Kathryn_Ruemmler" },
  { name: "Donald Trump Jr.", anchor: "Donald_Trump_Jr._and_Eric_Trump" },
  { name: "Sergei Belyakov", anchor: "Sergei_Belyakov" },
  { name: "Richard Branson", anchor: "Richard_Branson" },
  { name: "Flavio Briatore", anchor: "Flavio_Briatore" },
  { name: "Jean-Luc Brunel", anchor: "Jean-Luc_Brunel" },
  { name: "Lawrence Delson", anchor: "Lawrence_Delson" },
  { name: "Alan Dershowitz", anchor: "Alan_Dershowitz" },
  { name: "David Gelernter", anchor: "David_Gelernter" },
  { name: "Stephen Hawking", anchor: "Stephen_Hawking" },
  { name: "Stephen Kosslyn", anchor: "Stephen_Kosslyn" },
  { name: "Lawrence Krauss", anchor: "Lawrence_Krauss" },
  { name: "Miroslav Lajčák", anchor: "Miroslav_Lajčák" },
  { name: "Peter Mandelson", anchor: "Peter_Mandelson" },
  { name: "Matthew Menchel", anchor: "Matthew_Menchel" },
  { name: "Nathan Myhrvold", anchor: "Nathan_Myhrvold" },
  { name: "Stacey Plaskett", anchor: "Stacey_Plaskett" },
  { name: "Thomas Pritzker", anchor: "Thomas_Pritzker" },
  { name: "Casey Wasserman", anchor: "Casey_Wasserman" },
  { name: "Mark Zuckerberg", anchor: "Mark_Zuckerberg" },
  { name: "Naomi Campbell", anchor: "Naomi_Campbell" },
  { name: "Vitaly Churkin", anchor: "Vitaly_Churkin" },
  { name: "Sarah Ferguson", anchor: "Sarah_Ferguson" },
  { name: "Howard Lutnick", anchor: "Howard_Lutnick" },
  { name: "Nadia Marcinko", anchor: "Nadia_Marcinko" },
  { name: "Ashley Massaro", anchor: "Ashley_Massaro" },
  { name: "Robert Maxwell", anchor: "Robert_Maxwell" },
  { name: "Soon-Yi Previn", anchor: "Soon-Yi_Previn" },
  { name: "Andres Serrano", anchor: "Andres_Serrano" },
  { name: "Karyna Shuliak", anchor: "Karyna_Shuliak" },
  { name: "Robert Trivers", anchor: "Robert_Trivers" },
  { name: "Leon Botstein", anchor: "Leon_Botstein" },
  { name: "Edward Boyden", anchor: "Edward_Boyden" },
  { name: "John Brockman", anchor: "John_Brockman" },
  { name: "William Burns", anchor: "William_Burns" },
  { name: "Deepak Chopra", anchor: "Deepak_Chopra" },
  { name: "George Church", anchor: "George_Church" },
  { name: "Maria Drokova", anchor: "Maria_Drokova" },
  { name: "Andrew Farkas", anchor: "Andrew_Farkas" },
  { name: "Caroline Lang", anchor: "Caroline_Lang" },
  { name: "Ronald Lauder", anchor: "Ronald_Lauder" },
  { name: "Marvin Minsky", anchor: "Marvin_Minsky" },
  { name: "Robert Mugabe", anchor: "Robert_Mugabe" },
  { name: "Boris Nikolic", anchor: "Boris_Nikolic" },
  { name: "Steven Pinker", anchor: "Steven_Pinker" },
  { name: "Alberto Pinto", anchor: "Alberto_Pinto_and_Linda_Pinto" },
  { name: "David A. Ross", anchor: "David_A._Ross" },
  { name: "David Rowland", anchor: "David_Rowland" },
  { name: "Larry Summers", anchor: "Larry_Summers" },
  { name: "Amanda Thirsk", anchor: "Amanda_Thirsk" },
  { name: "Melania Trump", anchor: "Melania_Trump" },
  { name: "Brian Vickers", anchor: "Brian_Vickers" },
  { name: "Michael Wolff", anchor: "Michael_Wolff" },
  { name: "Richard Axel", anchor: "Richard_Axel" },
  { name: "Steve Bannon", anchor: "Steve_Bannon" },
  { name: "David Blaine", anchor: "David_Blaine" },
  { name: "Børge Brende", anchor: "Børge_Brende" },
  { name: "Noam Chomsky", anchor: "Noam_Chomsky" },
  { name: "Bill Clinton", anchor: "Bill_Clinton" },
  { name: "Gordon Getty", anchor: "Gordon_Getty" },
  { name: "Ben Goertzel", anchor: "Ben_Goertzel" },
  { name: "David Hanson", anchor: "David_Hanson" },
  { name: "Reid Hoffman", anchor: "Reid_Hoffman" },
  { name: "Brad S. Karp", anchor: "Brad_S._Karp" },
  { name: "Bobby Kotick", anchor: "Bobby_Kotick" },
  { name: "Julian Leese", anchor: "Julian_Leese" },
  { name: "Martin Nowak", anchor: "Martin_Nowak" },
  { name: "Jean Pigozzi", anchor: "Jean_Pigozzi" },
  { name: "Lisa Randall", anchor: "Lisa_Randall" },
  { name: "Brett Ratner", anchor: "Brett_Ratner" },
  { name: "David Schoen", anchor: "David_Schoen" },
  { name: "Roger Schank", anchor: "Roger_Schank" },
  { name: "Peggy Siegal", anchor: "Peggy_Siegal" },
  { name: "Kevin Spacey", anchor: "Kevin_Spacey" },
  { name: "Donald Trump", anchor: "Donald_Trump" },
  { name: "James Watson", anchor: "James_Watson" },
  { name: "Nathan Wolfe", anchor: "Nathan_Wolfe" },
  { name: "Woody Allen", anchor: "Woody_Allen" },
  { name: "Anil Ambani", anchor: "Anil_Ambani" },
  { name: "Peter Attia", anchor: "Peter_Attia" },
  { name: "Joscha Bach", anchor: "Joscha_Bach" },
  { name: "Tom Barrack", anchor: "Tom_Barrack" },
  { name: "Todd Boehly", anchor: "Todd_Boehly" },
  { name: "Sergey Brin", anchor: "Sergey_Brin" },
  { name: "Glenn Dubin", anchor: "Glenn_Dubin" },
  { name: "Josh Harris", anchor: "Josh_Harris" },
  { name: "Jack Horner", anchor: "Jack_Horner" },
  { name: "Mark Landon", anchor: "Mark_Landon" },
  { name: "Kimbal Musk", anchor: "Kimbal_Musk" },
  { name: "Linda Pinto", anchor: "Alberto_Pinto_and_Linda_Pinto" },
  { name: "John Phelan", anchor: "John_Phelan" },
  { name: "Daniel Siad", anchor: "Daniel_Siad" },
  { name: "David Stern", anchor: "David_Stern" },
  { name: "Peter Thiel", anchor: "Peter_Thiel" },
  { name: "Steve Tisch", anchor: "Steve_Tisch" },
  { name: "Dan Ariely", anchor: "Dan_Ariely" },
  { name: "Ehud Barak", anchor: "Ehud_Barak" },
  { name: "Leon Black", anchor: "Leon_Black" },
  { name: "Nick Candy", anchor: "Nick_Candy" },
  { name: "Bill Gates", anchor: "Bill_Gates" },
  { name: "Dean Kamen", anchor: "Dean_Kamen" },
  { name: "Nick Leese", anchor: "Nick_Leese" },
  { name: "Marc Rowan", anchor: "Marc_Rowan" },
  { name: "Kevin Rudd", anchor: "Kevin_Rudd" },
  { name: "Jes Staley", anchor: "Jes_Staley" },
  { name: "David Tang", anchor: "David_Tang" },
  { name: "Mark Tramo", anchor: "Mark_Tramo" },
  { name: "Eric Trump", anchor: "Donald_Trump_Jr._and_Eric_Trump" },
  { name: "Paul Tweed", anchor: "Paul_Tweed" },
  { name: "Karim Wade", anchor: "Karim_Wade" },
  { name: "Les Wexner", anchor: "Les_Wexner" },
  { name: "Doug Band", anchor: "Doug_Band" },
  { name: "Joe Gibbs", anchor: "Joe_Gibbs" },
  { name: "Mona Juul", anchor: "Mona_Juul" },
  { name: "Gary King", anchor: "Gary_King" },
  { name: "Jack Lang", anchor: "Jack_Lang" },
  { name: "Elon Musk", anchor: "Elon_Musk" },
  { name: "Elisa New", anchor: "Elisa_New" },
  { name: "Mehmet Oz", anchor: "Mehmet_Oz" },
  { name: "Al Seckel", anchor: "Al_Seckel" },
  { name: "Ken Starr", anchor: "Ken_Starr" },
  { name: "Jess Ting", anchor: "Jess_Ting" },
  { name: "Jean Todt", anchor: "Jean_Todt" },
  { name: "Joi Ito", anchor: "Joi_Ito" },
];
